# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7Lmfr7-IaMWXeRzfGjrOXKRosrzXeNN
"""

[] import numpy as np

list=[1,2,3,4,4,5,6]
print(list)

import numpy as np
list1=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(list1)
print("the array is",arr1)

"""3.identify their type using type()



"""

import numpy as np
list1=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(list1)
print("the array is",arr1)
print(type(list1))
print(type(arr1))

"""4.perfrom mathematical operation on these data sets created multiplication,division,poweroff

o
"""

import numpy as np
lst1=[1,2,3,4,5,6]
lst2=[10,11,12,13,14,15]
arr1=np.array(lst1)
arr2=np.array(lst2)
arr4=arr1+arr2
print('The sum ofthe two arrays is',arr4)
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,11,12,13,14,15])
arr3=arr1*arr2
arr4=arr1+arr2
arr5=arr2/arr1
arr6=arr2**arr1
print("The product  array is",arr3)
print("The sum array is",arr4)
print('The divided array is',arr5)
print("The poweroff array is",arr6)

"""5.combine text with numpy function to generate a textual output-"addition of two array1+array2

"""

import numpy as np
lst1=[1,2,3,4,5,6]
lst2=[10,11,12,13,14,15]
arr1=np.array(lst1)
arr2=np.array(lst2)
arr4=arr1+arr2
print('The sum ofthe two arrays is',arr4)

"""6.implementnp.sin(), log(), log2, np.exe())"""

import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([12,3,5,4,2])
arr3=np.sin(arr1)
arr4=np.cos(arr2)
arr5=np.tan(arr2)
arr6=np.log(arr1)
arr7=np.exp(arr1)
arr3=np.log2(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)

"""
















Part2-Visualization of data using matplotlib ,pyplots packages

1.Generate a data set for health care us using the following relations and justify the relationships among the vectors
3.scatter plot
"""

people = ['Arjun','Badshah','Chetan','David warner','Eminem','Fazal',
          'Gangotri','Harish','Imran','Julayi','Kathrina kaif','Lingesh']
age = [21,12,32,45,37,18,28,52,5,40,48,15]
weight = [55,35,77,68,70,60,72,69,18,65,82,48]
height = [160,135,170,165,173,168,175,159,105,171,155,158]
import matplotlib.pyplot as plt
plt.scatter(weight, height)
plt.title("Relationship between Weight and Height of Patients")
plt.ylabel("Height in Meters")
plt.xlabel("Weight of Patients in Kgs")
plt.show()

"""4.BAR chart"""

plt.figure(figsize=(12,4))
plt.title("People's weight in kgs",fontsize=16,
          fontstyle='italic')

# Main plot function 'bar'
plt.bar(x=people,height=weight, width=0.6,
                  color='orange',edgecolor='k',alpha=0.6)

plt.xlabel("People",fontsize=15)
plt.xticks(fontsize=14,rotation=30)
plt.yticks(fontsize=14)
plt.ylabel("Weight (in kgs)",fontsize=15)
plt.show()

"""5.Histogram
6.provide graph title,lables for X,Y axis with proper justification and explanation ofthe graph
"""

import numpy as np
plt.figure(figsize=(7,5))

# Main plot function 'hist'
plt.hist(weight,color='red',edgecolor='k', alpha=0.75,bins=5)

plt.title("Histogram of patient weight",fontsize=18)
plt.xlabel("Weight in kgs",fontsize=15)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()